= REST API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요
API 관리 문서 입니다.

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.(리소스가 없거나 수정/삭제에 해당하는 데이터가 존재하지 않을 경우)
|===

[[resources-Auth]]
== Auth

회원가입 및 로그인 관련 API를 요청할 때 사용한다.

[[resources-sign-up]]
=== 회원가입

`POST` 를 사용하여 회원가입을 요청한다.

operation::sign-up[snippets='curl-request,http-response,request-fields']

[[resources-sign-in]]
=== 로그인

`POST` 를 사용하여 로그인을 요청한다.

operation::sign-in[snippets='curl-request,http-response,request-fields']

[[resources-member]]
== Member

회원 데이터를 조회하거나 관리할 때 사용한다.

[[resources-member-find]]
=== 회원 단건 조회

`GET` 요청을 사용하여 회원을 조회한다.

operation::member-find[snippets='curl-request,http-response']

[[resources-member-query]]
=== 회원 쿼리 조회

`GET` 요청을 사용하여 회원 데이터를 쿼리한다.

operation::member-query[snippets='curl-request,http-response,request-parameters']

[[resources-member-update]]
=== 회원 수정

`PUT` 요청을 사용하여 회원 데이터를 수정한다.

operation::member-update[snippets='curl-request,http-response,request-fields']

[[resources-member-delete]]
=== 회원 삭제

`DELETE` 요청을 사용하여 회원 데이터를 삭제한다.

operation::member-delete[snippets='curl-request,http-response']

[[resources-member-delete-all]]
=== 회원 일괄 삭제

`DELETE` 요청을 사용하여 회원 데이터를 일괄 삭제한다.

operation::member-delete-all[snippets='curl-request,http-response']

[[resources-order]]
== Order

주문 데이터를 조회하거나 관리할 때 사용한다.

[[resources-order-find]]
=== 주문 단건 조회

`GET` 요청을 사용하여 주문 데이터를 조회한다.

operation::order-find[snippets='curl-request,http-response']

[[resources-order-query]]
=== 주문 쿼리 조회

`GET` 요청을 사용하여 주문 데이터를 쿼리한다.

operation::order-query[snippets='curl-request,http-response,request-parameters']

[[resources-order-create]]
=== 주문 등록

`POST` 요청을 사용하여 주문 데이터를 등록한다.

operation::order-create[snippets='curl-request,http-response,request-fields']
